### ISSUE TITLE
Refine onboarding process when landing on overview

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#182]
### Basic information:

OS (Android / iOS / both): Android 7.0
Version: 1.1.1-dev8

### Issue description:

Currently a new user lands on "Overview" with already selected currency networks, and no call-to-action, tutorial or any other information on what to do.

### Possible solution

Short-term fix: Direct the user to the below empty "Contacts" first time they enter the app

![image 2018-08-31 11 30 29](https://user-images.githubusercontent.com/18598519/44905179-9293a900-ad11-11e8-831d-c2c0c813c684.jpg)

**Comment by Kisgus** [comment]
@seichris could you please see if this problem is covered in our mockups?

**Comment by seichris** [comment]
![onboarding](https://user-images.githubusercontent.com/25006584/44667106-2d426e00-aa1a-11e8-8679-77b0725c4278.JPG)

The different cases are covered in [the mockups](https://www.figma.com/file/cnsEjp1Frfk9XRoTgl2YYbf1/Trustlines-App.-Sprint%3A-14.08.), but we need to refine them a little, because they were thought for basem to make them more beautiful.

**Comment by seichris** [comment]
New user comes to Contact screen.
Overview screen doesnt show any network. (networks are disabled in Account>Networks).

**Comment by dakingha69** [comment]
Partially solved via https://github.com/trustlines-network/mobileapp/commit/6f8bcaf6138032f114274df9764e61a6dd95988d.

**Comment by Kisgus** [comment]
Thanks
